import React from 'react'
import Head from 'next/head'
import DrList from '../components/DrList'
import { useEffect } from 'react'
import Container from '../components/Container'
import LoadingBar from '../components/LoadingBar'

export default function About({openModal}) {
  useEffect(() => {
    document.querySelector("body").className = "";
    document.querySelector("body").classList.add("bg-about")
   },[])
  return (
    <>
    <Head>
        <title>About | Bridgepointe Family Dental Care</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${process.env.NEXT_PUBLIC_IMAGESPATH}/favicon.ico`} />
      </Head>
<LoadingBar/>
<Container openModal={openModal}/>
       <DrList/>

    </>
  )
}
