import React from 'react'
import Head from 'next/head'
import SrvList from '../components/SrvList'
import { useEffect } from 'react'
import Container from '../components/Container'
import LoadingBar from '../components/LoadingBar'
export default function Services({openModal}) {
  useEffect(() => {
    document.querySelector("body").className = "";
    document.querySelector("body").classList.add("bg-services")
   },[])
  return (
    <>
      <Head>
        <title>Services | Bridgepointe Family Dental Care</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <LoadingBar/>
<Container openModal={openModal}/>
      <SrvList/>
    </>
  )
}
